### ISSUE TITLE
bump version?

### ISSUE THREAD

**Issue by codefromthecrypt** [tbroyer/jaxrs-utils#1]
heya, I would like to use this in brave to test jaxrs tracing performance w/okhttp3. I noticed you've made some progress. Mind cutting a new version?

**Comment by tbroyer** [comment]
There you go, version 1.1 for both resteasy-client-okhttp{,3}; just give Sonatype OSSRH some time to sync to Central.

Fwiw, I hesitated between 1.0.1 and 1.1 as the version number, but chose 1.1 as I updated the dependencies to the latest OkHttp versions (in addition to a bugfix).

**Comment by codefromthecrypt** [comment]
Fantastic! I'll use it tonight!
